### ISSUE TITLE
0-ary function definitions

### ISSUE THREAD

**Issue by jwaldmann** [noschinl/cyp#22]
Because of #12 , I tried
```
append = append
```
but this was rejected by the parser. 
```
      Parsing background theory
          Parsing function definition 'append = append'
              Invalid function definition
 ```
I think it should be accepted, since it is syntactically valid Haskell. 

This special case `foo = foo` perhaps is only needed for this work-around, but `foo = bar` might actually occur.

**Comment by jwaldmann** [comment]
fixed by https://gitlab.imn.htwk-leipzig.de/waldmann/cyp/commit/63a5db1a0d1ca7d1ba211b554f362831c2cdcd8e

**Comment by larsrh** [comment]
Thanks, cherry-picked as 6ff7b50.
