### ISSUE TITLE
update for current ghc and haskell-src-exts

### ISSUE THREAD

**Issue by jwaldmann** [noschinl/cyp#8]
Hi, 

I am forking your project at https://gitlab.imn.htwk-leipzig.de/waldmann/cyp  because I want to use this with the Leipzig autotool system (cf. https://gitlab.imn.htwk-leipzig.de/autotool/all0/issues/39 )

As a first step, I patched cyp to work with recent haskell-src-exts. 
* all AST nodes have source location info now (which we ignore?)
* the Match type (https://hackage.haskell.org/package/haskell-src-exts-1.19.1/docs/Language-Haskell-Exts-Syntax.html#t:Match ) now has two constructors (which we conflate?)

I am getting 4 failed tests (see https://gitlab.imn.htwk-leipzig.de/waldmann/cyp/builds/3770 , https://gitlab.imn.htwk-leipzig.de/waldmann/cyp/builds/3770/artifacts/file/test.text ) is this expected?

**Comment by larsrh** [comment]
I'm trying to reproduce this now. With the dependencies as they're specified currently, the tests all pass. Currently setting up stack to figure out when exactly it broke.

**Comment by larsrh** [comment]
@jwaldmann You can track my progress in #9

**Comment by larsrh** [comment]
I have a hunch. I took your code porting from haskell-src-exts 1.17 to 1.18 and had a look at the parse trees. Turns out the following change breaks it:

```diff
 data AbsTerm a
     = Application (AbsTerm a) (AbsTerm a)
     | Const String
     | Free a
     | Schematic a
-    | Literal Literal
+    | Literal (Literal Location)
     deriving (Show, Eq)
```

This now means that locations are being compared in the derived `Eq` instance. The workaround based on top of your code would be a custom `Eq` instance:

```haskell
instance Eq a => Eq (AbsTerm a) where
    (Application a1 a2) == (Application b1 b2) = a1 == b1 && a2 == b2
    (Const c1) == (Const c2) = c1 == c2
    (Free f1) == (Free f2) = f1 == f2
    (Schematic s1) == (Schematic s2) = s1 == s2
    (Literal l1) == (Literal l2) = fmap (const ()) l1 == fmap (const ()) l2
    _ == _ = False
```

or to amend your patch this way:

```diff
 data AbsTerm a
     = Application (AbsTerm a) (AbsTerm a)
     | Const String
     | Free a
     | Schematic a
-    | Literal Literal
+    | Literal (Literal ())
     deriving (Show, Eq)
```

I'd be much more sympathetic towards the latter version, unless there's any reason why locations must be stored in our internal terms.

**Comment by jwaldmann** [comment]
Nice observation. Storing location was just laziness on my part (it's what the HSE parser returns). Of course since it was not there earlier, cyp does not currently use it. But perhaps it wants to, in the future?

Work-around: just `fmap (const ())` on the parsed tree?

**Comment by larsrh** [comment]
> But perhaps it wants to, in the future?

Possibly, but we can make it so on demand.

> Work-around: just `fmap (const ())` on the parsed tree?

Sounds good. Would you mind sending a reworked patch based on 1956d772158b17b9095e9d502cc80cc9e6f1ea44 (which uses `lts-7`)?

**Comment by jwaldmann** [comment]
I replaced `deriving Eq` by the hand-written `Eq` instance, as you suggested. (You could cherry-pick https://gitlab.imn.htwk-leipzig.de/waldmann/cyp/commit/aaa931eb5ca3ea5a605f11ee868f6cba53b76191 )

lts-7.29 has haskell-src-exts-1.17.1 which (compared to lts-8.5 with h-s-e-1.18) has non-generic srclocs, and different arity  for Literal (https://www.stackage.org/haddock/lts-7.20/haskell-src-exts-1.17.1/Language-Haskell-Exts-Syntax.html#t:Literal https://www.stackage.org/haddock/lts-8.5/haskell-src-exts-1.18.2/Language-Haskell-Exts-Syntax.html#t:Literal ) Yes, this is annoying. They manage to break this every 6 months or so ...
